import type { Metadata } from 'next'

import QueryWrapper from './lib/components/QueryWrapper'
import { ScrollToWrapper } from './lib/components/ScrollTo'

import AppLayout from './lib/components/AppLayout'
import { StoreProvider } from './lib/hooks/useStore/StoreProvider'

import '@/app/lib/assets/styles/index.sass'


export const metadata: Metadata = {
  title: 'maytry: main',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ru'>
      <body>
        <QueryWrapper>
          <StoreProvider>
            <ScrollToWrapper>
              <AppLayout>
                {children}
              </AppLayout>
            </ScrollToWrapper>
          </StoreProvider>
        </QueryWrapper>
      </body>
    </html>
  )
}
