import type { Metadata } from 'next'

import QueryWrapper from './lib/components/QueryWrapper'
import { ScrollToWrapper } from './lib/components/ScrollTo'

import '@/app/lib/assets/styles/index.sass'
import AppLayout from './lib/components/AppLayout'


export const metadata: Metadata = {
  title: 'maytry: main',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ru'>
      <body>
        <QueryWrapper>
          <ScrollToWrapper>
            <AppLayout>
              {children}
            </AppLayout>
          </ScrollToWrapper>
        </QueryWrapper>
      </body>
    </html>
  )
}
